VarNotSetException: Use a generic email template
To be able to reuse the email notification templated for other exceptions than
the VarNotSetExceptions, a generic template is generated and the
VarNotSetException specific explanation is moved into the exception message.

Signed-off-by: Anna-Maria Gleixner <anna-maria@linutronix.de>
Reviewed-by: Benedikt Spranger <b.spranger@linutronix.de>